---
- name: Your First Custom Module
  hosts: localhost
  gather_facts: false
  connection: local
 
  tasks:
    - name: Show Version
      action: ex_custom_module_2 host="192.168.4.47" username="cisco" password="CiscoCisco1"
      register: output

    - debug:
        var: output
