---
- name: Ansible Group and Host Varibles
  hosts: localhost

  tasks:
    - name: create router configuration files
      template: 
        src=~/git/Python_for_Networks/Lab_3_Ansible/Lab_3_3_Network_Device_Next_Layer/Include/nxos.j2
        dest=~/git/Python_for_Networks/Lab_3_Ansible/Lab_3_3_Network_Device_Next_Layer/Include/{{ item.key }}.conf
      with_dict: "{{ nexus_devices }}"
      register: output    

    - include: show_output.yml
