---
IOS_R1:
    hostname: '192.168.4.51'
    port: 22
    username: 'cisco'
    password: 'cisco'
    platform: 'cisco_ios'

IOS_R2:
    hostname: '192.168.4.52'
    port: 22
    username: 'cisco'
    password: 'cisco'
    platform: 'cisco_ios'
